### ISSUE TITLE
Add remove all from SET

### ISSUE THREAD

**Issue by vbudhram** [RiptideElements/mightycache#12]
Add the ability to remove all from cache. Similar functionality to [Redis FlushAll](http://redis.io/commands/FLUSHALL)

**Comment by DavidTPate** [comment]
What's the use case for this? I wouldn't expect most web services to expose some way for a consumer of an API to clear out an entire cache.

**Comment by vbudhram** [comment]
I believe the functionality I am really looking for is to remove all from a set. Updated ticket issue. I will take a look and see what needs to be done to add this.
